#!/usr/bin/env python3
"""Mirror build target — generate the portable mirror and compile it 64-bit.

For every TU in tools/mirror/build_manifest.txt this:
  1. runs the P2 rewriter (passes.apply_pointer_rules) on the decomp source,
  2. writes the transformed TU to mirror/src/<path>,
  3. compiles it 64-bit with the decomp include tree.

A listed TU that fails to compile fails the build (exit 1). This is the seed of
the native-64-bit ship target from ADR 0001: it grows one TU at a time as more of
the engine becomes mirror-compilable.

  python3 tools/mirror/build_mirror.py            # generate + compile all
  python3 tools/mirror/build_mirror.py --gen-only # just regenerate mirror/src
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(HERE))
import passes  # noqa: E402

DECOMP = REPO / "decomp"
MIRROR = REPO / "mirror"
MANIFEST = HERE / "build_manifest.txt"
CC = "clang"
INCLUDES = ["-Idecomp/include", "-Idecomp", "-Idecomp/src", "-Imirror/runtime"]
CFLAGS = ["-m64", "-c", "-w", "-O1"]


def read_manifest() -> list[str]:
    out = []
    for ln in MANIFEST.read_text().splitlines():
        ln = ln.strip()
        if ln and not ln.startswith("#"):
            out.append(ln)
    return out


def gen_one(rel: str, rules: dict) -> tuple[Path, int, int]:
    """Emit the mirror TU. Returns (mirror_path, crit_before, crit_after)."""
    src = DECOMP / rel
    text = src.read_text(errors="replace")
    tu_rel = f"decomp/{rel}"
    before = sum(1 for f in passes.scan_text_pointer_width(text, tu_rel)
                 if f.severity == "critical")
    new_text, applied, _ = passes.apply_pointer_rules(text, rules, tu_rel)
    if applied and "uintptr_t" in new_text and "stdint.h" not in new_text:
        new_text = "#include <stdint.h>\n" + new_text
    after = sum(1 for f in passes.scan_text_pointer_width(new_text, tu_rel)
                if f.severity == "critical")
    dst = MIRROR / "src" / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    header = (f"/* GENERATED by tools/mirror/build_mirror.py from decomp/{rel}\n"
              f" * passes=[P0,P1,P2,P6]  DO NOT EDIT — edit mirror/rules/ + regenerate. */\n")
    dst.write_text(header + new_text)
    return dst, before, after


def compile_one(mirror_path: Path) -> tuple[bool, str]:
    r = subprocess.run([CC, *CFLAGS, *INCLUDES, str(mirror_path),
                        "-o", str(mirror_path.with_suffix(".o"))],
                       capture_output=True, text=True, cwd=REPO)
    return r.returncode == 0, r.stderr


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate + compile the mirror target")
    ap.add_argument("--gen-only", action="store_true", help="regenerate mirror/src, skip compile")
    args = ap.parse_args(argv)

    tus = read_manifest()
    rules = passes.load_pointer_rules(MIRROR / "rules")
    # The generator owns mirror/src exclusively, so it always equals the manifest
    # (no strays from ad-hoc --emit runs leak into the CMake glob).
    shutil.rmtree(MIRROR / "src", ignore_errors=True)
    print(f"mirror target: {len(tus)} TU(s)")

    n_fail = 0
    tot_before = tot_after = 0
    for rel in tus:
        mpath, cb, ca = gen_one(rel, rules)
        tot_before += cb
        tot_after += ca
        if args.gen_only:
            print(f"  gen  {rel}  crit {cb}->{ca}")
            continue
        ok, err = compile_one(mpath)
        status = "ok " if ok else "FAIL"
        note = "" if cb == ca == 0 else f"  crit {cb}->{ca}"
        print(f"  [{status}] {rel}{note}")
        if not ok:
            n_fail += 1
            first = err.strip().splitlines()[:4]
            for l in first:
                print(f"        {l}")

    verb = "generated" if args.gen_only else "compiled"
    print(f"\n{len(tus) - n_fail}/{len(tus)} {verb}; "
          f"pointer-width criticals {tot_before} -> {tot_after}")
    return 1 if n_fail else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
