#!/usr/bin/env python3
"""Regenerate mirror/rules/mapblock_hoststruct.toml (the map-block HOST-STRUCT pass
plus shader texture slots holding IDs).

Each rewrite is matched against the CURRENT output of every other rule and must
occur exactly once on its line, found by content near the expected line.

  rm mirror/rules/mapblock_hoststruct.toml && python3 tools/mirror/gen_mapblock_hoststruct_rules.py
"""
import sys
sys.path.insert(0, 'tools/mirror')
import passes
from pathlib import Path

OUT = Path('mirror/rules/mapblock_hoststruct.toml')
rules = passes.load_pointer_rules(Path('mirror/rules'))
cur, out = {}, []


def text(f):
    if f not in cur:
        cur[f] = passes.apply_pointer_rules(Path(f).read_text(errors='replace'), rules, f)[0].splitlines()
    return cur[f]


def rep(f, near, frm, to, why):
    lines = text(f)
    cands = [near] if frm in lines[near - 1] else \
        [l for l in range(max(1, near - 15), near + 16) if frm in lines[l - 1]]
    if len(cands) != 1:
        raise SystemExit(f"{f}:~{near}: {len(cands)} candidate lines for {frm!r}: {cands}")
    ln = cands[0]
    if lines[ln - 1].count(frm) != 1:
        raise SystemExit(f"{f}:{ln}: {frm!r} occurs {lines[ln - 1].count(frm)} times")
    lines[ln - 1] = lines[ln - 1].replace(frm, to)
    out.append((f, ln, frm, to, why))


def resolve(expr):
    """a shader texture slot read as a pointer -> resolve its ID"""
    return f"((Texture*)textureIdxToPtr({expr[:-len('.texture')] if expr.endswith('.texture') else expr[:-len('->texture')]}"\
           f"{'.' if expr.endswith('.texture') else '->'}textureIndex))"


TD, TX = 'decomp/src/main/tex_dolphin.c', 'decomp/src/main/texture.c'
# --- map block loader --------------------------------------------------------------
rep(TD, 1621, "loadAndDecompressDataFile(MLDF_FILEID_BLOCKS_BIN_A, buf, blockOff, compressedLen, 0, 0, 0);",
    "buf = stairfax_mapblock_load_unpacked(buf, decompressedSize, blockOff, compressedLen);",
    "load + transcode to host layout (mirror/runtime/stairfax_mapblock.c)")
rep(TD, 982, " : (0xCC008000)", "",
    "MWCC fixed-address syntax spelled out; AT_ADDRESS expands to nothing off-MWCC")
# --- texture ID lookup, defined where the loaded-texture table is visible ----------
rep(TX, 97, "}", "} int stairfax_texture_id_of(void* texture) { int i; for (i = 0; i < gLoadedTextureCount; i++) "
    "{ if (gLoadedTextures[i].texture == (u8*)texture) return i + 1; } return 0; }",
    "after textureIdxToPtr: the ID of a loaded (pinned) texture; same line, so no line shifts")
# --- MapBlock_initShaders: shader slots get IDs; the table keeps the pinned pointers --
rep(TD, 1480, "sh->layers[j].texture = block->textures[ref].texture;",
    "sh->layers[j].textureIndex = stairfax_texture_id_of(block->textures[ref].texture);",
    "shader slot holds the texture's ID")
rep(TD, 1484, "mapTextureOverrideAcquire(sh->layers[j].texture,",
    "mapTextureOverrideAcquire((Texture*)textureIdxToPtr(sh->layers[j].textureIndex),",
    "the override table keys on the texture pointer")
rep(TD, 1496, "sh->auxTexture = block->textures[ref].texture;",
    "sh->auxTextureIndex = stairfax_texture_id_of(block->textures[ref].texture);",
    "shader slot holds the texture's ID")
# --- direct pointer readers of shader texture slots resolve the ID ----------------
for f, near, expr in [
        ('decomp/src/dlls/objects/308_texscroll2/texscroll2.c', 61, "shader->layers[materialIndex].texture"),
        ('decomp/src/dlls/objects/662_WCTempleDia/WCTempleDia.c', 50, "entry->layers[0].texture"),
        ('decomp/src/dlls/objects/662_WCTempleDia/WCTempleDia.c', 54, "entry->layers[0].texture"),
        ('decomp/src/main/shader.c', 1547, "shaderLayer->texture"),
        ('decomp/src/main/shader.c', 2475, "shaderLayer->texture"),
        ('decomp/src/main/shader_dolphin.c', 818, "((Shader*)p1)->layers[0].texture"),
        (TD, 257, "((ShaderLayer*)Shader_getLayer(shader, 0))->texture"),
        (TD, 689, "layer->texture"), (TD, 710, "layer->texture"), (TD, 736, "layer->texture"),
        (TD, 757, "layer->texture"), (TD, 782, "layer->texture")]:
    rep(f, near, expr, resolve(expr), "shader texture slots hold IDs (texture_ids.toml)")

lines = ['''# Map blocks in the HOST layout (pointer-slot survey item 2: HOST-STRUCT), and
# shader texture slots holding IDs (survey item 3; texture_ids.toml).
#
# mirror/runtime/stairfax_mapblock.c loads a block and transcodes MapBlockData,
# its Shader table and its display-list records to host layout. Map textures stay
# pinned pointers in the block's own table (the override table and textureFree
# key on them); shader slots get each texture's loaded-texture ID, and the code
# that read slots as pointers resolves the ID with textureIdxToPtr.
# Generated by tools/mirror/gen_mapblock_hoststruct_rules.py; comments say why.
''']
q = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
for f, ln, frm, to, why in out:
    lines.append(f'[[text.replace]]\nfile = "{f}"\nline = {ln}  # {why}\nfrom = "{q(frm)}"\nto = "{q(to)}"\n')
OUT.write_text("\n".join(lines))
print(len(out), "text.replace rules ->", OUT)
