/* GENERATED by tools/mirror/gen_layouts.py from decomp/include/main/map_block.h.
 * DO NOT EDIT; re-run the generator.
 *
 * GameCube -> host transcoders for on-disc structs (HOST-STRUCT): MapBlockData, MapBlockBoundsRec.
 * Each copies every scalar leaf from its GameCube (big-endian, 32-bit) offset
 * to its host offset. Pointer leaves are 4-byte disc values stored
 * zero-extended; relocating them is the caller's job. Unions transcode their
 * first member (the on-disc meaning). */
#ifndef STAIRFAX_GEN_MAPBLOCK_LAYOUT_H
#define STAIRFAX_GEN_MAPBLOCK_LAYOUT_H
#include <stdint.h>
#include <string.h>
#include "main/map_block.h"
#include "gen_model_layout.h"

#define SFX_GC_SIZEOF_MapBlockData 0xa4
_Static_assert(sizeof(MapBlockData) == 0xe0, "MapBlockData: host layout changed; re-run gen_layouts.py");
static inline void sfx_unpack_MapBlockData(const uint8_t* gc, MapBlockData* host)
{
    uint8_t* h = (uint8_t*)host;
    memset(host, 0, sizeof(MapBlockData));
    { uintptr_t v = sfx_be32(gc + 0x0); memcpy(h + 0x0, &v, sizeof v); }  /* unused00 */
    { uint16_t v = sfx_be16(gc + 0x4); memcpy(h + 0x8, &v, 2); }  /* flags4 */
    { uint16_t v = sfx_be16(gc + 0x6); memcpy(h + 0xa, &v, 2); }  /* unk6 */
    { uint32_t v = sfx_be32(gc + 0x8); memcpy(h + 0xc, &v, 4); }  /* size */
    { uint32_t v = sfx_be32(gc + 0xc); memcpy(h + 0x10, &v, 4); }  /* transform[0][0] */
    { uint32_t v = sfx_be32(gc + 0x10); memcpy(h + 0x14, &v, 4); }  /* transform[0][1] */
    { uint32_t v = sfx_be32(gc + 0x14); memcpy(h + 0x18, &v, 4); }  /* transform[0][2] */
    { uint32_t v = sfx_be32(gc + 0x18); memcpy(h + 0x1c, &v, 4); }  /* transform[0][3] */
    { uint32_t v = sfx_be32(gc + 0x1c); memcpy(h + 0x20, &v, 4); }  /* transform[1][0] */
    { uint32_t v = sfx_be32(gc + 0x20); memcpy(h + 0x24, &v, 4); }  /* transform[1][1] */
    { uint32_t v = sfx_be32(gc + 0x24); memcpy(h + 0x28, &v, 4); }  /* transform[1][2] */
    { uint32_t v = sfx_be32(gc + 0x28); memcpy(h + 0x2c, &v, 4); }  /* transform[1][3] */
    { uint32_t v = sfx_be32(gc + 0x2c); memcpy(h + 0x30, &v, 4); }  /* transform[2][0] */
    { uint32_t v = sfx_be32(gc + 0x30); memcpy(h + 0x34, &v, 4); }  /* transform[2][1] */
    { uint32_t v = sfx_be32(gc + 0x34); memcpy(h + 0x38, &v, 4); }  /* transform[2][2] */
    { uint32_t v = sfx_be32(gc + 0x38); memcpy(h + 0x3c, &v, 4); }  /* transform[2][3] */
    h[0x40] = gc[0x3c];  /* pad3C[0] */
    h[0x41] = gc[0x3d];  /* pad3C[1] */
    h[0x42] = gc[0x3e];  /* pad3C[2] */
    h[0x43] = gc[0x3f];  /* pad3C[3] */
    h[0x44] = gc[0x40];  /* pad3C[4] */
    h[0x45] = gc[0x41];  /* pad3C[5] */
    h[0x46] = gc[0x42];  /* pad3C[6] */
    h[0x47] = gc[0x43];  /* pad3C[7] */
    h[0x48] = gc[0x44];  /* pad3C[8] */
    h[0x49] = gc[0x45];  /* pad3C[9] */
    h[0x4a] = gc[0x46];  /* pad3C[10] */
    h[0x4b] = gc[0x47];  /* pad3C[11] */
    h[0x4c] = gc[0x48];  /* pad3C[12] */
    h[0x4d] = gc[0x49];  /* pad3C[13] */
    h[0x4e] = gc[0x4a];  /* pad3C[14] */
    h[0x4f] = gc[0x4b];  /* pad3C[15] */
    { uintptr_t v = sfx_be32(gc + 0x4c); memcpy(h + 0x50, &v, sizeof v); }  /* gcPolygons */
    { uintptr_t v = sfx_be32(gc + 0x50); memcpy(h + 0x58, &v, sizeof v); }  /* polygonGroups */
    { uintptr_t v = sfx_be32(gc + 0x54); memcpy(h + 0x60, &v, sizeof v); }  /* textures */
    { uintptr_t v = sfx_be32(gc + 0x58); memcpy(h + 0x68, &v, sizeof v); }  /* vertices */
    { uintptr_t v = sfx_be32(gc + 0x5c); memcpy(h + 0x70, &v, sizeof v); }  /* vertexColors */
    { uintptr_t v = sfx_be32(gc + 0x60); memcpy(h + 0x78, &v, sizeof v); }  /* vertexTexCoords */
    { uintptr_t v = sfx_be32(gc + 0x64); memcpy(h + 0x80, &v, sizeof v); }  /* shaders */
    { uintptr_t v = sfx_be32(gc + 0x68); memcpy(h + 0x88, &v, sizeof v); }  /* displayLists */
    h[0x90] = gc[0x6c];  /* pad6C[0] */
    h[0x91] = gc[0x6d];  /* pad6C[1] */
    h[0x92] = gc[0x6e];  /* pad6C[2] */
    h[0x93] = gc[0x6f];  /* pad6C[3] */
    { uintptr_t v = sfx_be32(gc + 0x70); memcpy(h + 0x98, &v, sizeof v); }  /* hits */
    { uintptr_t v = sfx_be32(gc + 0x74); memcpy(h + 0xa0, &v, sizeof v); }  /* auxData */
    { uintptr_t v = sfx_be32(gc + 0x78); memcpy(h + 0xa8, &v, sizeof v); }  /* renderInstrsMain */
    { uintptr_t v = sfx_be32(gc + 0x7c); memcpy(h + 0xb0, &v, sizeof v); }  /* renderInstrsTransp */
    { uintptr_t v = sfx_be32(gc + 0x80); memcpy(h + 0xb8, &v, sizeof v); }  /* renderInstrsWater */
    { uint16_t v = sfx_be16(gc + 0x84); memcpy(h + 0xc0, &v, 2); }  /* nRenderInstrsMain */
    { uint16_t v = sfx_be16(gc + 0x86); memcpy(h + 0xc2, &v, 2); }  /* nRenderInstrsTransp */
    { uint16_t v = sfx_be16(gc + 0x88); memcpy(h + 0xc4, &v, 2); }  /* nRenderInstrsWater */
    { uint16_t v = sfx_be16(gc + 0x8a); memcpy(h + 0xc6, &v, 2); }  /* minY */
    { uint16_t v = sfx_be16(gc + 0x8c); memcpy(h + 0xc8, &v, 2); }  /* maxY */
    { uint16_t v = sfx_be16(gc + 0x8e); memcpy(h + 0xca, &v, 2); }  /* collisionYOffset */
    { uint16_t v = sfx_be16(gc + 0x90); memcpy(h + 0xcc, &v, 2); }  /* vertexCount */
    { uint16_t v = sfx_be16(gc + 0x92); memcpy(h + 0xce, &v, 2); }  /* unk92 */
    { uint16_t v = sfx_be16(gc + 0x94); memcpy(h + 0xd0, &v, 2); }  /* colorCount */
    { uint16_t v = sfx_be16(gc + 0x96); memcpy(h + 0xd2, &v, 2); }  /* texCoordCount */
    { uint16_t v = sfx_be16(gc + 0x98); memcpy(h + 0xd4, &v, 2); }  /* nPolygons */
    { uint16_t v = sfx_be16(gc + 0x9a); memcpy(h + 0xd6, &v, 2); }  /* polyGroupCount */
    { uint16_t v = sfx_be16(gc + 0x9c); memcpy(h + 0xd8, &v, 2); }  /* hitCount */
    { uint16_t v = sfx_be16(gc + 0x9e); memcpy(h + 0xda, &v, 2); }  /* unk9E */
    h[0xdc] = gc[0xa0];  /* textureCount */
    h[0xdd] = gc[0xa1];  /* displayListCount */
    h[0xde] = gc[0xa2];  /* shaderCount */
    h[0xdf] = gc[0xa3];  /* padA3 */
}

#define SFX_GC_SIZEOF_MapBlockBoundsRec 0x1c
_Static_assert(sizeof(MapBlockBoundsRec) == 0x20, "MapBlockBoundsRec: host layout changed; re-run gen_layouts.py");
static inline void sfx_unpack_MapBlockBoundsRec(const uint8_t* gc, MapBlockBoundsRec* host)
{
    uint8_t* h = (uint8_t*)host;
    memset(host, 0, sizeof(MapBlockBoundsRec));
    { uintptr_t v = sfx_be32(gc + 0x0); memcpy(h + 0x0, &v, sizeof v); }  /* dlist */
    { uint16_t v = sfx_be16(gc + 0x4); memcpy(h + 0x8, &v, 2); }  /* dlistSize */
    { uint16_t v = sfx_be16(gc + 0x6); memcpy(h + 0xa, &v, 2); }  /* minX */
    { uint16_t v = sfx_be16(gc + 0x8); memcpy(h + 0xc, &v, 2); }  /* minY */
    { uint16_t v = sfx_be16(gc + 0xa); memcpy(h + 0xe, &v, 2); }  /* minZ */
    { uint16_t v = sfx_be16(gc + 0xc); memcpy(h + 0x10, &v, 2); }  /* maxX */
    { uint16_t v = sfx_be16(gc + 0xe); memcpy(h + 0x12, &v, 2); }  /* maxY */
    { uint16_t v = sfx_be16(gc + 0x10); memcpy(h + 0x14, &v, 2); }  /* maxZ */
    h[0x16] = gc[0x12];  /* flags */
    h[0x17] = gc[0x13];  /* shaderIndex */
    { uint16_t v = sfx_be16(gc + 0x14); memcpy(h + 0x18, &v, 2); }  /* renderBitOffset */
    h[0x1a] = gc[0x16];  /* pad16[0] */
    h[0x1b] = gc[0x17];  /* pad16[1] */
    h[0x1c] = gc[0x18];  /* selector */
    h[0x1d] = gc[0x19];  /* pad19[0] */
    h[0x1e] = gc[0x1a];  /* pad19[1] */
    h[0x1f] = gc[0x1b];  /* pad19[2] */
}

#endif
