/* GENERATED by tools/mirror/gen_layouts.py from decomp/include/main/model.h.
 * DO NOT EDIT; re-run the generator.
 *
 * GameCube -> host transcoders for on-disc structs (HOST-STRUCT): ModelFileHeader, Shader, ModelDisplayListEntry, ModelVtxAnimChunk.
 * Each copies every scalar leaf from its GameCube (big-endian, 32-bit) offset
 * to its host offset. Pointer leaves are 4-byte disc values stored
 * zero-extended; relocating them is the caller's job. Unions transcode their
 * first member (the on-disc meaning). */
#ifndef STAIRFAX_GEN_MODEL_LAYOUT_H
#define STAIRFAX_GEN_MODEL_LAYOUT_H
#include <stdint.h>
#include <string.h>
#include "main/model.h"

static inline uint16_t sfx_be16(const uint8_t* p) { return (uint16_t)(p[0] << 8 | p[1]); }
static inline uint32_t sfx_be32(const uint8_t* p)
{ return (uint32_t)p[0] << 24 | (uint32_t)p[1] << 16 | (uint32_t)p[2] << 8 | p[3]; }

#define SFX_GC_SIZEOF_ModelFileHeader 0xfc
_Static_assert(sizeof(ModelFileHeader) == 0x180, "ModelFileHeader: host layout changed; re-run gen_layouts.py");
static inline void sfx_unpack_ModelFileHeader(const uint8_t* gc, ModelFileHeader* host)
{
    uint8_t* h = (uint8_t*)host;
    memset(host, 0, sizeof(ModelFileHeader));
    h[0x0] = gc[0x0];  /* refCount */
    h[0x1] = gc[0x1];  /* unk01 */
    { uint16_t v = sfx_be16(gc + 0x2); memcpy(h + 0x2, &v, 2); }  /* flags */
    { uint16_t v = sfx_be16(gc + 0x4); memcpy(h + 0x4, &v, 2); }  /* modelId */
    h[0x6] = gc[0x6];  /* unk06[0] */
    h[0x7] = gc[0x7];  /* unk06[1] */
    h[0x8] = gc[0x8];  /* unk06[2] */
    h[0x9] = gc[0x9];  /* unk06[3] */
    h[0xa] = gc[0xa];  /* unk06[4] */
    h[0xb] = gc[0xb];  /* unk06[5] */
    { uint32_t v = sfx_be32(gc + 0xc); memcpy(h + 0xc, &v, 4); }  /* dataSize */
    h[0x10] = gc[0x10];  /* unk10[0] */
    h[0x11] = gc[0x11];  /* unk10[1] */
    h[0x12] = gc[0x12];  /* unk10[2] */
    h[0x13] = gc[0x13];  /* unk10[3] */
    h[0x14] = gc[0x14];  /* unk10[4] */
    h[0x15] = gc[0x15];  /* unk10[5] */
    h[0x16] = gc[0x16];  /* unk10[6] */
    h[0x17] = gc[0x17];  /* unk10[7] */
    { uintptr_t v = sfx_be32(gc + 0x18); memcpy(h + 0x18, &v, sizeof v); }  /* unk18 */
    { uintptr_t v = sfx_be32(gc + 0x1c); memcpy(h + 0x20, &v, sizeof v); }  /* unk1C */
    { uintptr_t v = sfx_be32(gc + 0x20); memcpy(h + 0x28, &v, sizeof v); }  /* textureIds */
    h[0x30] = gc[0x24];  /* flags24 */
    h[0x31] = gc[0x25];  /* unk25[0] */
    h[0x32] = gc[0x26];  /* unk25[1] */
    h[0x33] = gc[0x27];  /* unk25[2] */
    { uintptr_t v = sfx_be32(gc + 0x28); memcpy(h + 0x38, &v, sizeof v); }  /* vertices */
    { uintptr_t v = sfx_be32(gc + 0x2c); memcpy(h + 0x40, &v, sizeof v); }  /* normals */
    { uintptr_t v = sfx_be32(gc + 0x30); memcpy(h + 0x48, &v, sizeof v); }  /* colors */
    { uintptr_t v = sfx_be32(gc + 0x34); memcpy(h + 0x50, &v, sizeof v); }  /* texCoords */
    { uintptr_t v = sfx_be32(gc + 0x38); memcpy(h + 0x58, &v, sizeof v); }  /* renderOps */
    { uintptr_t v = sfx_be32(gc + 0x3c); memcpy(h + 0x60, &v, sizeof v); }  /* jointData */
    { uintptr_t v = sfx_be32(gc + 0x40); memcpy(h + 0x68, &v, sizeof v); }  /* jointBlendData */
    { uint32_t v = sfx_be32(gc + 0x44); memcpy(h + 0x70, &v, 4); }  /* vertexAnimPivot[0] */
    { uint32_t v = sfx_be32(gc + 0x48); memcpy(h + 0x74, &v, 4); }  /* vertexAnimPivot[1] */
    { uint32_t v = sfx_be32(gc + 0x4c); memcpy(h + 0x78, &v, 4); }  /* vertexAnimPivot[2] */
    { uint32_t v = sfx_be32(gc + 0x50); memcpy(h + 0x7c, &v, 4); }  /* vertexAnimScaleDivisor */
    { uintptr_t v = sfx_be32(gc + 0x54); memcpy(h + 0x80, &v, sizeof v); }  /* extraJointDefs */
    { uintptr_t v = sfx_be32(gc + 0x58); memcpy(h + 0x88, &v, sizeof v); }  /* hitVolumes */
    { uintptr_t v = sfx_be32(gc + 0x5c); memcpy(h + 0x90, &v, sizeof v); }  /* collisionTriangles */
    { uintptr_t v = sfx_be32(gc + 0x60); memcpy(h + 0x98, &v, sizeof v); }  /* collisionBlocks */
    { uintptr_t v = sfx_be32(gc + 0x64); memcpy(h + 0xa0, &v, sizeof v); }  /* animationModelPtrs */
    { uintptr_t v = sfx_be32(gc + 0x68); memcpy(h + 0xa8, &v, sizeof v); }  /* animationDataSection */
    { uintptr_t v = sfx_be32(gc + 0x6c); memcpy(h + 0xb0, &v, sizeof v); }  /* animationHeaderBuffer */
    { uint16_t v = sfx_be16(gc + 0x70); memcpy(h + 0xb8, &v, 2); }  /* animGroupBaseIndices[0] */
    { uint16_t v = sfx_be16(gc + 0x72); memcpy(h + 0xba, &v, 2); }  /* animGroupBaseIndices[1] */
    { uint16_t v = sfx_be16(gc + 0x74); memcpy(h + 0xbc, &v, 2); }  /* animGroupBaseIndices[2] */
    { uint16_t v = sfx_be16(gc + 0x76); memcpy(h + 0xbe, &v, 2); }  /* animGroupBaseIndices[3] */
    { uint16_t v = sfx_be16(gc + 0x78); memcpy(h + 0xc0, &v, 2); }  /* animGroupBaseIndices[4] */
    { uint16_t v = sfx_be16(gc + 0x7a); memcpy(h + 0xc2, &v, 2); }  /* animGroupBaseIndices[5] */
    { uint16_t v = sfx_be16(gc + 0x7c); memcpy(h + 0xc4, &v, 2); }  /* animGroupBaseIndices[6] */
    { uint16_t v = sfx_be16(gc + 0x7e); memcpy(h + 0xc6, &v, 2); }  /* animGroupBaseIndices[7] */
    { uint32_t v = sfx_be32(gc + 0x80); memcpy(h + 0xc8, &v, 4); }  /* animationDataFileOffset */
    { uint16_t v = sfx_be16(gc + 0x84); memcpy(h + 0xcc, &v, 2); }  /* headerSize */
    h[0xce] = gc[0x86];  /* unk86[0] */
    h[0xcf] = gc[0x87];  /* unk86[1] */
    h[0xd0] = gc[0x88];  /* unk86[2] */
    h[0xd1] = gc[0x89];  /* unk86[3] */
    { uint16_t v = sfx_be16(gc + 0x8a); memcpy(h + 0xd2, &v, 2); }  /* vertexAnimCount */
    h[0xd4] = gc[0x8c];  /* unk8C[0] */
    h[0xd5] = gc[0x8d];  /* unk8C[1] */
    h[0xd6] = gc[0x8e];  /* unk8C[2] */
    h[0xd7] = gc[0x8f];  /* unk8C[3] */
    h[0xd8] = gc[0x90];  /* unk8C[4] */
    h[0xd9] = gc[0x91];  /* unk8C[5] */
    h[0xda] = gc[0x92];  /* unk8C[6] */
    h[0xdb] = gc[0x93];  /* unk8C[7] */
    { uintptr_t v = sfx_be32(gc + 0x94); memcpy(h + 0xe0, &v, sizeof v); }  /* vertexAnimEntriesRaw */
    h[0xe8] = gc[0x98];  /* unk98[0] */
    h[0xe9] = gc[0x99];  /* unk98[1] */
    h[0xea] = gc[0x9a];  /* unk98[2] */
    h[0xeb] = gc[0x9b];  /* unk98[3] */
    h[0xec] = gc[0x9c];  /* unk98[4] */
    h[0xed] = gc[0x9d];  /* unk98[5] */
    h[0xee] = gc[0x9e];  /* unk98[6] */
    h[0xef] = gc[0x9f];  /* unk98[7] */
    h[0xf0] = gc[0xa0];  /* unk98[8] */
    h[0xf1] = gc[0xa1];  /* unk98[9] */
    h[0xf2] = gc[0xa2];  /* unk98[10] */
    h[0xf3] = gc[0xa3];  /* unk98[11] */
    { uintptr_t v = sfx_be32(gc + 0xa4); memcpy(h + 0xf8, &v, sizeof v); }  /* vertexAnimEntries */
    { uintptr_t v = sfx_be32(gc + 0xa8); memcpy(h + 0x100, &v, sizeof v); }  /* vertexAnimBase */
    h[0x108] = gc[0xac];  /* unkAC[0] */
    h[0x109] = gc[0xad];  /* unkAC[1] */
    { uint16_t v = sfx_be16(gc + 0xae); memcpy(h + 0x10a, &v, 2); }  /* blendAnimCount */
    h[0x10c] = gc[0xb0];  /* unkB0[0] */
    h[0x10d] = gc[0xb1];  /* unkB0[1] */
    h[0x10e] = gc[0xb2];  /* unkB0[2] */
    h[0x10f] = gc[0xb3];  /* unkB0[3] */
    h[0x110] = gc[0xb4];  /* unkB0[4] */
    h[0x111] = gc[0xb5];  /* unkB0[5] */
    h[0x112] = gc[0xb6];  /* unkB0[6] */
    h[0x113] = gc[0xb7];  /* unkB0[7] */
    { uintptr_t v = sfx_be32(gc + 0xb8); memcpy(h + 0x118, &v, sizeof v); }  /* blendAnimEntriesRaw */
    h[0x120] = gc[0xbc];  /* unkBC[0] */
    h[0x121] = gc[0xbd];  /* unkBC[1] */
    h[0x122] = gc[0xbe];  /* unkBC[2] */
    h[0x123] = gc[0xbf];  /* unkBC[3] */
    h[0x124] = gc[0xc0];  /* unkBC[4] */
    h[0x125] = gc[0xc1];  /* unkBC[5] */
    h[0x126] = gc[0xc2];  /* unkBC[6] */
    h[0x127] = gc[0xc3];  /* unkBC[7] */
    h[0x128] = gc[0xc4];  /* unkBC[8] */
    h[0x129] = gc[0xc5];  /* unkBC[9] */
    h[0x12a] = gc[0xc6];  /* unkBC[10] */
    h[0x12b] = gc[0xc7];  /* unkBC[11] */
    { uintptr_t v = sfx_be32(gc + 0xc8); memcpy(h + 0x130, &v, sizeof v); }  /* blendAnimEntries */
    { uintptr_t v = sfx_be32(gc + 0xcc); memcpy(h + 0x138, &v, sizeof v); }  /* blendAnimBase */
    { uintptr_t v = sfx_be32(gc + 0xd0); memcpy(h + 0x140, &v, sizeof v); }  /* displayLists */
    { uintptr_t v = sfx_be32(gc + 0xd4); memcpy(h + 0x148, &v, sizeof v); }  /* instrs */
    { uint16_t v = sfx_be16(gc + 0xd8); memcpy(h + 0x150, &v, 2); }  /* instrsBitLenWords */
    h[0x152] = gc[0xda];  /* unkDA[0] */
    h[0x153] = gc[0xdb];  /* unkDA[1] */
    { uintptr_t v = sfx_be32(gc + 0xdc); memcpy(h + 0x158, &v, sizeof v); }  /* morphTargetPtrs */
    { uint16_t v = sfx_be16(gc + 0xe0); memcpy(h + 0x160, &v, 2); }  /* cullDistance */
    { uint16_t v = sfx_be16(gc + 0xe2); memcpy(h + 0x162, &v, 2); }  /* shaderFlags */
    { uint16_t v = sfx_be16(gc + 0xe4); memcpy(h + 0x164, &v, 2); }  /* vertexCount */
    { uint16_t v = sfx_be16(gc + 0xe6); memcpy(h + 0x166, &v, 2); }  /* normalCount */
    { uint16_t v = sfx_be16(gc + 0xe8); memcpy(h + 0x168, &v, 2); }  /* colorCount */
    { uint16_t v = sfx_be16(gc + 0xea); memcpy(h + 0x16a, &v, 2); }  /* texCoordCount */
    { uint16_t v = sfx_be16(gc + 0xec); memcpy(h + 0x16c, &v, 2); }  /* animationCount */
    h[0x16e] = gc[0xee];  /* unkEE[0] */
    h[0x16f] = gc[0xef];  /* unkEE[1] */
    { uint16_t v = sfx_be16(gc + 0xf0); memcpy(h + 0x170, &v, 2); }  /* collisionBlockCount */
    h[0x172] = gc[0xf2];  /* textureCount */
    h[0x173] = gc[0xf3];  /* jointCount */
    h[0x174] = gc[0xf4];  /* extraJointCount */
    h[0x175] = gc[0xf5];  /* displayListCount */
    h[0x176] = gc[0xf6];  /* shadowDisplayListCount */
    h[0x177] = gc[0xf7];  /* hitVolumeCount */
    h[0x178] = gc[0xf8];  /* renderOpCount */
    h[0x179] = gc[0xf9];  /* morphTargetCount */
    h[0x17a] = gc[0xfa];  /* texMtxCount */
}

#define SFX_GC_SIZEOF_Shader 0x44
_Static_assert(sizeof(Shader) == 0x68, "Shader: host layout changed; re-run gen_layouts.py");
static inline void sfx_unpack_Shader(const uint8_t* gc, Shader* host)
{
    uint8_t* h = (uint8_t*)host;
    memset(host, 0, sizeof(Shader));
    h[0x0] = gc[0x0];  /* pad00[0] */
    h[0x1] = gc[0x1];  /* pad00[1] */
    h[0x2] = gc[0x2];  /* pad00[2] */
    h[0x3] = gc[0x3];  /* pad00[3] */
    h[0x4] = gc[0x4];  /* pad00[4] */
    h[0x5] = gc[0x5];  /* pad00[5] */
    h[0x6] = gc[0x6];  /* pad00[6] */
    h[0x7] = gc[0x7];  /* pad00[7] */
    { uintptr_t v = sfx_be32(gc + 0x8); memcpy(h + 0x8, &v, sizeof v); }  /* reg1Texture */
    h[0x10] = gc[0xc];  /* alpha */
    h[0x11] = gc[0xd];  /* pad0D[0] */
    h[0x12] = gc[0xe];  /* pad0D[1] */
    h[0x13] = gc[0xf];  /* pad0D[2] */
    h[0x14] = gc[0x10];  /* pad0D[3] */
    h[0x15] = gc[0x11];  /* pad0D[4] */
    h[0x16] = gc[0x12];  /* pad0D[5] */
    h[0x17] = gc[0x13];  /* pad0D[6] */
    { uintptr_t v = sfx_be32(gc + 0x14); memcpy(h + 0x18, &v, sizeof v); }  /* reg2Texture */
    { uint32_t v = sfx_be32(gc + 0x18); memcpy(h + 0x20, &v, 4); }  /* textureId */
    { uint32_t v = sfx_be32(gc + 0x1c); memcpy(h + 0x24, &v, 4); }  /* unk1C */
    h[0x28] = gc[0x20];  /* reg2TexSlot */
    h[0x29] = gc[0x21];  /* pad21 */
    h[0x2a] = gc[0x22];  /* reg2Alpha */
    h[0x2b] = gc[0x23];  /* pad23 */
    { uint32_t v = sfx_be32(gc + 0x24); memcpy(h + 0x30, &v, 4); }  /* layers[0].textureIndex */
    h[0x38] = gc[0x28];  /* layers[0].typeBits */
    h[0x39] = gc[0x29];  /* layers[0].materialId */
    h[0x3a] = gc[0x2a];  /* layers[0].scrollMtx */
    h[0x3b] = gc[0x2b];  /* layers[0].unk7 */
    { uint32_t v = sfx_be32(gc + 0x2c); memcpy(h + 0x40, &v, 4); }  /* layers[1].textureIndex */
    h[0x48] = gc[0x30];  /* layers[1].typeBits */
    h[0x49] = gc[0x31];  /* layers[1].materialId */
    h[0x4a] = gc[0x32];  /* layers[1].scrollMtx */
    h[0x4b] = gc[0x33];  /* layers[1].unk7 */
    { uint32_t v = sfx_be32(gc + 0x34); memcpy(h + 0x50, &v, 4); }  /* auxTextureIndex */
    { uint32_t v = sfx_be32(gc + 0x38); memcpy(h + 0x58, &v, 4); }  /* indTextureId */
    { uint32_t v = sfx_be32(gc + 0x3c); memcpy(h + 0x60, &v, 4); }  /* flags */
    h[0x64] = gc[0x40];  /* vtxAttrFlags */
    h[0x65] = gc[0x41];  /* layerCount */
    h[0x66] = gc[0x42];  /* envMapParams */
    h[0x67] = gc[0x43];  /* alphaOverride */
}

#define SFX_GC_SIZEOF_ModelDisplayListEntry 0x1c
_Static_assert(sizeof(ModelDisplayListEntry) == 0x20, "ModelDisplayListEntry: host layout changed; re-run gen_layouts.py");
static inline void sfx_unpack_ModelDisplayListEntry(const uint8_t* gc, ModelDisplayListEntry* host)
{
    uint8_t* h = (uint8_t*)host;
    memset(host, 0, sizeof(ModelDisplayListEntry));
    { uintptr_t v = sfx_be32(gc + 0x0); memcpy(h + 0x0, &v, sizeof v); }  /* dlist */
    { uint16_t v = sfx_be16(gc + 0x4); memcpy(h + 0x8, &v, 2); }  /* dlistSize */
    h[0xa] = gc[0x6];  /* pad06[0] */
    h[0xb] = gc[0x7];  /* pad06[1] */
    h[0xc] = gc[0x8];  /* pad06[2] */
    h[0xd] = gc[0x9];  /* pad06[3] */
    h[0xe] = gc[0xa];  /* pad06[4] */
    h[0xf] = gc[0xb];  /* pad06[5] */
    h[0x10] = gc[0xc];  /* pad06[6] */
    h[0x11] = gc[0xd];  /* pad06[7] */
    h[0x12] = gc[0xe];  /* pad06[8] */
    h[0x13] = gc[0xf];  /* pad06[9] */
    h[0x14] = gc[0x10];  /* pad06[10] */
    h[0x15] = gc[0x11];  /* pad06[11] */
    h[0x16] = gc[0x12];  /* pad06[12] */
    h[0x17] = gc[0x13];  /* pad06[13] */
    h[0x18] = gc[0x14];  /* pad06[14] */
    h[0x19] = gc[0x15];  /* pad06[15] */
    h[0x1a] = gc[0x16];  /* pad06[16] */
    h[0x1b] = gc[0x17];  /* pad06[17] */
    h[0x1c] = gc[0x18];  /* pad06[18] */
    h[0x1d] = gc[0x19];  /* pad06[19] */
    h[0x1e] = gc[0x1a];  /* pad06[20] */
    h[0x1f] = gc[0x1b];  /* pad06[21] */
}

#define SFX_GC_SIZEOF_ModelVtxAnimChunk 0x74
_Static_assert(sizeof(ModelVtxAnimChunk) == 0x80, "ModelVtxAnimChunk: host layout changed; re-run gen_layouts.py");
static inline void sfx_unpack_ModelVtxAnimChunk(const uint8_t* gc, ModelVtxAnimChunk* host)
{
    uint8_t* h = (uint8_t*)host;
    memset(host, 0, sizeof(ModelVtxAnimChunk));
    h[0x0] = gc[0x0];  /* unk00[0] */
    h[0x1] = gc[0x1];  /* unk00[1] */
    h[0x2] = gc[0x2];  /* unk00[2] */
    h[0x3] = gc[0x3];  /* unk00[3] */
    h[0x4] = gc[0x4];  /* unk00[4] */
    h[0x5] = gc[0x5];  /* unk00[5] */
    h[0x6] = gc[0x6];  /* unk00[6] */
    h[0x7] = gc[0x7];  /* unk00[7] */
    h[0x8] = gc[0x8];  /* unk00[8] */
    h[0x9] = gc[0x9];  /* unk00[9] */
    h[0xa] = gc[0xa];  /* unk00[10] */
    h[0xb] = gc[0xb];  /* unk00[11] */
    h[0xc] = gc[0xc];  /* unk00[12] */
    h[0xd] = gc[0xd];  /* unk00[13] */
    h[0xe] = gc[0xe];  /* unk00[14] */
    h[0xf] = gc[0xf];  /* unk00[15] */
    h[0x10] = gc[0x10];  /* unk00[16] */
    h[0x11] = gc[0x11];  /* unk00[17] */
    h[0x12] = gc[0x12];  /* unk00[18] */
    h[0x13] = gc[0x13];  /* unk00[19] */
    h[0x14] = gc[0x14];  /* unk00[20] */
    h[0x15] = gc[0x15];  /* unk00[21] */
    h[0x16] = gc[0x16];  /* unk00[22] */
    h[0x17] = gc[0x17];  /* unk00[23] */
    h[0x18] = gc[0x18];  /* unk00[24] */
    h[0x19] = gc[0x19];  /* unk00[25] */
    h[0x1a] = gc[0x1a];  /* unk00[26] */
    h[0x1b] = gc[0x1b];  /* unk00[27] */
    h[0x1c] = gc[0x1c];  /* unk00[28] */
    h[0x1d] = gc[0x1d];  /* unk00[29] */
    h[0x1e] = gc[0x1e];  /* unk00[30] */
    h[0x1f] = gc[0x1f];  /* unk00[31] */
    h[0x20] = gc[0x20];  /* unk00[32] */
    h[0x21] = gc[0x21];  /* unk00[33] */
    h[0x22] = gc[0x22];  /* unk00[34] */
    h[0x23] = gc[0x23];  /* unk00[35] */
    h[0x24] = gc[0x24];  /* unk00[36] */
    h[0x25] = gc[0x25];  /* unk00[37] */
    h[0x26] = gc[0x26];  /* unk00[38] */
    h[0x27] = gc[0x27];  /* unk00[39] */
    h[0x28] = gc[0x28];  /* unk00[40] */
    h[0x29] = gc[0x29];  /* unk00[41] */
    h[0x2a] = gc[0x2a];  /* unk00[42] */
    h[0x2b] = gc[0x2b];  /* unk00[43] */
    h[0x2c] = gc[0x2c];  /* unk00[44] */
    h[0x2d] = gc[0x2d];  /* unk00[45] */
    h[0x2e] = gc[0x2e];  /* unk00[46] */
    h[0x2f] = gc[0x2f];  /* unk00[47] */
    h[0x30] = gc[0x30];  /* unk00[48] */
    h[0x31] = gc[0x31];  /* unk00[49] */
    h[0x32] = gc[0x32];  /* unk00[50] */
    h[0x33] = gc[0x33];  /* unk00[51] */
    h[0x34] = gc[0x34];  /* unk00[52] */
    h[0x35] = gc[0x35];  /* unk00[53] */
    h[0x36] = gc[0x36];  /* unk00[54] */
    h[0x37] = gc[0x37];  /* unk00[55] */
    h[0x38] = gc[0x38];  /* unk00[56] */
    h[0x39] = gc[0x39];  /* unk00[57] */
    h[0x3a] = gc[0x3a];  /* unk00[58] */
    h[0x3b] = gc[0x3b];  /* unk00[59] */
    h[0x3c] = gc[0x3c];  /* unk00[60] */
    h[0x3d] = gc[0x3d];  /* unk00[61] */
    h[0x3e] = gc[0x3e];  /* unk00[62] */
    h[0x3f] = gc[0x3f];  /* unk00[63] */
    h[0x40] = gc[0x40];  /* unk00[64] */
    h[0x41] = gc[0x41];  /* unk00[65] */
    h[0x42] = gc[0x42];  /* unk00[66] */
    h[0x43] = gc[0x43];  /* unk00[67] */
    h[0x44] = gc[0x44];  /* unk00[68] */
    h[0x45] = gc[0x45];  /* unk00[69] */
    h[0x46] = gc[0x46];  /* unk00[70] */
    h[0x47] = gc[0x47];  /* unk00[71] */
    h[0x48] = gc[0x48];  /* unk00[72] */
    h[0x49] = gc[0x49];  /* unk00[73] */
    h[0x4a] = gc[0x4a];  /* unk00[74] */
    h[0x4b] = gc[0x4b];  /* unk00[75] */
    h[0x4c] = gc[0x4c];  /* unk00[76] */
    h[0x4d] = gc[0x4d];  /* unk00[77] */
    h[0x4e] = gc[0x4e];  /* unk00[78] */
    h[0x4f] = gc[0x4f];  /* unk00[79] */
    h[0x50] = gc[0x50];  /* unk00[80] */
    h[0x51] = gc[0x51];  /* unk00[81] */
    h[0x52] = gc[0x52];  /* unk00[82] */
    h[0x53] = gc[0x53];  /* unk00[83] */
    h[0x54] = gc[0x54];  /* unk00[84] */
    h[0x55] = gc[0x55];  /* unk00[85] */
    h[0x56] = gc[0x56];  /* unk00[86] */
    h[0x57] = gc[0x57];  /* unk00[87] */
    h[0x58] = gc[0x58];  /* unk00[88] */
    h[0x59] = gc[0x59];  /* unk00[89] */
    h[0x5a] = gc[0x5a];  /* unk00[90] */
    h[0x5b] = gc[0x5b];  /* unk00[91] */
    h[0x5c] = gc[0x5c];  /* unk00[92] */
    h[0x5d] = gc[0x5d];  /* unk00[93] */
    h[0x5e] = gc[0x5e];  /* unk00[94] */
    h[0x5f] = gc[0x5f];  /* unk00[95] */
    { uint32_t v = sfx_be32(gc + 0x60); memcpy(h + 0x60, &v, 4); }  /* srcDataOffset */
    { uintptr_t v = sfx_be32(gc + 0x64); memcpy(h + 0x68, &v, sizeof v); }  /* weightStream */
    h[0x70] = gc[0x68];  /* unk68[0] */
    h[0x71] = gc[0x69];  /* unk68[1] */
    h[0x72] = gc[0x6a];  /* unk68[2] */
    h[0x73] = gc[0x6b];  /* unk68[3] */
    h[0x74] = gc[0x6c];  /* mtxIdxA */
    h[0x75] = gc[0x6d];  /* mtxIdxB */
    h[0x76] = gc[0x6e];  /* unk6E */
    h[0x77] = gc[0x6f];  /* weightWords */
    { uint16_t v = sfx_be16(gc + 0x70); memcpy(h + 0x78, &v, 2); }  /* vtxCount */
    h[0x7a] = gc[0x72];  /* dstByteOffset */
    h[0x7b] = gc[0x73];  /* vtxWords */
}

#endif
